### ISSUE TITLE
[BUG] uhm

### ISSUE THREAD

**Issue by syntheticlol** [real-fbdn/Supreme-Grabber#1]
this is my code dude what the flip stop skidding!

**Comment by real-fbdn** [comment]
This isn't my code, however it isn't yours, it was from another open-source grabber (JJZ) that has been removed so it is impossible to give credit.

**Comment by real-fbdn** [comment]
> > This isn't FULLY my code, however it isn't yours, it was from another open-source grabber (JJZ) that has been removed so it is impossible to give credit.
> 
> it is my code im the creator of JJZ

JJZ dosen't exist anymore. Plus  it's not all jjz code.

**Comment by syntheticlol** [comment]
> > > This isn't FULLY my code, however it isn't yours, it was from another open-source grabber (JJZ) that has been removed so it is impossible to give credit.
> > 
> > 
> > it is my code im the creator of JJZ
> 
> JJZ dosen't exist anymore. Plus it's not all jjz code.

the fuck are you talking about 💀 go to my profile click on vypix i named it vypix but jjz as a JOKE it has 31 stars

**Comment by real-fbdn** [comment]
As a JOKE??? You expect me to believe that

**Comment by syntheticlol** [comment]
> As a JOKE??? You expect me to believe that

bro look at my code 😭 its the same thing as yours i made ts like months ago dawg

**Comment by real-fbdn** [comment]
And you made jjz? Yeah right

**Comment by syntheticlol** [comment]
> And you made jjz? Yeah right

bro why would i lie its a shit post literally
