### ISSUE TITLE
Misunderstanding [FIXED]

### ISSUE THREAD

**Issue by Aideninnit123** [real-fbdn/Supreme-Grabber#2]
I sent the exe file to the person and the webhook did not send any data back

**Comment by Aideninnit123** [comment]
Is there any other things i have to do other than the setup?

**Comment by Aideninnit123** [comment]
Or do i have to send it on something other than discord

**Comment by Aideninnit123** [comment]
![image_2023-10-26_204230012](https://github.com/real-fbdn/Supreme-Grabber/assets/149107501/8c676160-4ce3-421d-b649-2f5b651455bb)

**Comment by Aideninnit123** [comment]
that was what i sent

**Comment by real-fbdn** [comment]
Hello! Thanks for making a issue, I will look into your problem but are you sure the person opened it?

**Comment by real-fbdn** [comment]
Also if the problem persists and I can't fix it, I have another grabber which is OP in-making. I can't be sure how long it'll take but expect 1-2 weeks. :)

**Comment by Aideninnit123** [comment]
Oh well if they have to open it dont u think its a bit flawed? its a dodgy looking .exe file lol so why would they

**Comment by real-fbdn** [comment]
It's impossible to have one that takes their information withour running any sort of application. As dodgy as it looks, its over powered once they open it

**Comment by Aideninnit123** [comment]
is there a way i can convince them to open it?

**Comment by real-fbdn** [comment]
That's up for you to decide. You can say it's a executor????? Or something. If you enjoy it please leave a star as we are only on 3!
