### ISSUE TITLE
webhook leak

### ISSUE THREAD

**Issue by 0xbitx** [real-fbdn/Supreme-Grabber#8]
webhook = 'https://discord.com/api/webhooks/1137689025025679501/i-eNJb_D_TEQHHktxetcTCAp5rBx8QOw9htf3_vxbSP-jwesHJ2XcuP54fkK8J-EGy3i'

**Comment by real-fbdn** [comment]
![image](https://github.com/real-fbdn/Supreme-Grabber/assets/142435308/336ff126-4958-44fe-af8b-0b7ee88cc698)
 no lol
